jobs:
  test:
    executor:
      name: go/default
      tag: "1.13"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          command: |
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python get-pip.py
            pip install -r requirements.txt
            wget --quiet https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
            sudo unzip terraform_0.12.20_linux_amd64.zip -d /usr/local/bin
            wget --quiet https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
            sudo unzip packer_1.5.5_linux_amd64.zip -d /usr/local/bin
          name: Install Terraform
      - run:
          command: go test ~/project/test -v -timeout 45m
          no_output_timeout: 45m
          name: "go test"

orbs:
  go: circleci/go@1.5.0
version: 2.1
workflows:
  default:
    jobs:
      - test:
          context: aws-ci-1
  version: 2
