name: TF 12 Integration Tests
on: push

jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25

      - name: Run Go Tests
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          pip install -r requirements.txt
          wget --quiet https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
          sudo unzip packer_1.5.5_linux_amd64.zip -d /usr/local/bin
          
      - name: Run Go Tests
        run: make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}